# Generated by Django 3.0.2 on 2020-02-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
