# Generated by Django 3.0.2 on 2020-02-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_delete_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_order'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['division_order'], 'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['office_order'], 'verbose_name': 'Office', 'verbose_name_plural': 'Offices'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['person_order'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AddField(
            model_name='department',
            name='department_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='division',
            name='division_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='office',
            name='office_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='person_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
