# Generated by Django 3.0.2 on 2020-02-11 05:10

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200211_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='office',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Office'),
        ),
    ]
