# Generated by Django 3.0.2 on 2020-02-11 05:14

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20200211_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='department',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='division',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Division'),
        ),
        migrations.AlterField(
            model_name='person',
            name='office',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Office'),
        ),
    ]
