# Generated by Django 3.0.2 on 2020-02-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20200211_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(db_index=True, help_text='yyyy-mm-dd', verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Surname'),
        ),
    ]
