# Generated by Django 3.0.2 on 2020-02-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20200211_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='url',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
