# Generated by Django 3.0.2 on 2020-02-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20200211_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='url',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
