# Generated by Django 3.0.2 on 2020-02-11 12:40

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20200211_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='office',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='staff.Office'),
        ),
        migrations.AlterField(
            model_name='division',
            name='department',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='staff.Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='staff.Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='division',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='staff.Division'),
        ),
        migrations.AlterField(
            model_name='person',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='staff.Office'),
        ),
    ]
