# Generated by Django 3.0.2 on 2020-02-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20200211_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_order',
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_acceptance_date',
            field=models.DateField(blank=True, help_text='yyyy-mm-dd', null=True, verbose_name='Job Acceptance Date'),
        ),
    ]
