# Generated by Django 3.0.2 on 2020-02-13 07:12

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_remove_department_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['office'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_order',
        ),
        migrations.AddField(
            model_name='department',
            name='office',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='staff.Office'),
        ),
    ]
