# Generated by Django 3.0.2 on 2020-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_auto_20200213_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_order'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='department',
            name='department_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
