# Generated by Django 3.0.2 on 2020-02-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_department_department_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['office'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_order',
        ),
    ]
