# Generated by Django 3.0.2 on 2020-02-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_auto_20200213_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
