# Generated by Django 3.0.2 on 2020-02-13 08:21

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_auto_20200213_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='office',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='staff.Office'),
        ),
    ]
