# Generated by Django 3.0.2 on 2020-02-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_auto_20200213_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='independent',
            field=models.BooleanField(default=False),
        ),
    ]
