# Generated by Django 3.0.2 on 2020-02-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_office_independent'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='division',
            name='independent',
            field=models.BooleanField(default=False),
        ),
    ]
