# Generated by Django 3.0.2 on 2020-02-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_auto_20200214_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='independent',
            field=models.BooleanField(default=True),
        ),
    ]
