# Generated by Django 3.0.2 on 2020-02-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_auto_20200214_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='url',
            field=models.SlugField(default=models.CharField(db_index=True, max_length=120, verbose_name='Name'), max_length=120, unique=True),
        ),
    ]
